/* tslint:disable */
/* eslint-disable */
/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AdminconversationsekmListOriginalConnectedChannelInfoResponse } from '../models';
// @ts-ignore
import { AdminconversationsekmListOriginalConnectedChannelInfodefaultResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AdminConversationsEkmApi - axios parameter creator
 * @export
 */
export const AdminConversationsEkmApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM.
         * @param {string} token Authentication token. Requires scope: &#x60;admin.conversations:read&#x60;
         * @param {string} [channelIds] A comma-separated list of channels to filter to.
         * @param {string} [teamIds] A comma-separated list of the workspaces to which the channels you would like returned belong.
         * @param {number} [limit] The maximum number of items to return. Must be between 1 - 1000 both inclusive.
         * @param {string} [cursor] Set &#x60;cursor&#x60; to &#x60;next_cursor&#x60; returned by the previous call to list items in the next page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOriginalConnectedChannelInfo: async (token: string, channelIds?: string, teamIds?: string, limit?: number, cursor?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('listOriginalConnectedChannelInfo', 'token', token)
            const localVarPath = `/admin.conversations.ekm.listOriginalConnectedChannelInfo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication slackAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "slackAuth", ["admin.conversations:read"], configuration)
            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            if (channelIds !== undefined) {
                localVarQueryParameter['channel_ids'] = channelIds;
            }

            if (teamIds !== undefined) {
                localVarQueryParameter['team_ids'] = teamIds;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/admin.conversations.ekm.listOriginalConnectedChannelInfo',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminConversationsEkmApi - functional programming interface
 * @export
 */
export const AdminConversationsEkmApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminConversationsEkmApiAxiosParamCreator(configuration)
    return {
        /**
         * List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM.
         * @param {AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOriginalConnectedChannelInfo(requestParameters: AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminconversationsekmListOriginalConnectedChannelInfoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOriginalConnectedChannelInfo(requestParameters.token, requestParameters.channelIds, requestParameters.teamIds, requestParameters.limit, requestParameters.cursor, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AdminConversationsEkmApi - factory interface
 * @export
 */
export const AdminConversationsEkmApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminConversationsEkmApiFp(configuration)
    return {
        /**
         * List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM.
         * @param {AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOriginalConnectedChannelInfo(requestParameters: AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest, options?: AxiosRequestConfig): AxiosPromise<AdminconversationsekmListOriginalConnectedChannelInfoResponse> {
            return localVarFp.listOriginalConnectedChannelInfo(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listOriginalConnectedChannelInfo operation in AdminConversationsEkmApi.
 * @export
 * @interface AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest
 */
export type AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest = {
    
    /**
    * Authentication token. Requires scope: `admin.conversations:read`
    * @type {string}
    * @memberof AdminConversationsEkmApiListOriginalConnectedChannelInfo
    */
    readonly token: string
    
    /**
    * A comma-separated list of channels to filter to.
    * @type {string}
    * @memberof AdminConversationsEkmApiListOriginalConnectedChannelInfo
    */
    readonly channelIds?: string
    
    /**
    * A comma-separated list of the workspaces to which the channels you would like returned belong.
    * @type {string}
    * @memberof AdminConversationsEkmApiListOriginalConnectedChannelInfo
    */
    readonly teamIds?: string
    
    /**
    * The maximum number of items to return. Must be between 1 - 1000 both inclusive.
    * @type {number}
    * @memberof AdminConversationsEkmApiListOriginalConnectedChannelInfo
    */
    readonly limit?: number
    
    /**
    * Set `cursor` to `next_cursor` returned by the previous call to list items in the next page.
    * @type {string}
    * @memberof AdminConversationsEkmApiListOriginalConnectedChannelInfo
    */
    readonly cursor?: string
    
}

/**
 * AdminConversationsEkmApiGenerated - object-oriented interface
 * @export
 * @class AdminConversationsEkmApiGenerated
 * @extends {BaseAPI}
 */
export class AdminConversationsEkmApiGenerated extends BaseAPI {
    /**
     * List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM.
     * @param {AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminConversationsEkmApiGenerated
     */
    public listOriginalConnectedChannelInfo(requestParameters: AdminConversationsEkmApiListOriginalConnectedChannelInfoRequest, options?: AxiosRequestConfig) {
        return AdminConversationsEkmApiFp(this.configuration).listOriginalConnectedChannelInfo(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
