/* tslint:disable */
/* eslint-disable */
/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AppspermissionsresourcesGetResourcesListResponse } from '../models';
// @ts-ignore
import { AppspermissionsresourcesGetResourcesListdefaultResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AppsPermissionsResourcesApi - axios parameter creator
 * @export
 */
export const AppsPermissionsResourcesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns list of resource grants this app has on a team.
         * @param {string} token Authentication token. Requires scope: &#x60;none&#x60;
         * @param {string} [cursor] Paginate through collections of data by setting the &#x60;cursor&#x60; parameter to a &#x60;next_cursor&#x60; attribute returned by a previous request\&#39;s &#x60;response_metadata&#x60;. Default value fetches the first \&quot;page\&quot; of the collection. See [pagination](https://slack.dev) for more detail.
         * @param {number} [limit] The maximum number of items to return.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResourcesList: async (token: string, cursor?: string, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('getResourcesList', 'token', token)
            const localVarPath = `/apps.permissions.resources.list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication slackAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "slackAuth", ["none"], configuration)
            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/apps.permissions.resources.list',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppsPermissionsResourcesApi - functional programming interface
 * @export
 */
export const AppsPermissionsResourcesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppsPermissionsResourcesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns list of resource grants this app has on a team.
         * @param {AppsPermissionsResourcesApiGetResourcesListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getResourcesList(requestParameters: AppsPermissionsResourcesApiGetResourcesListRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppspermissionsresourcesGetResourcesListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getResourcesList(requestParameters.token, requestParameters.cursor, requestParameters.limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AppsPermissionsResourcesApi - factory interface
 * @export
 */
export const AppsPermissionsResourcesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppsPermissionsResourcesApiFp(configuration)
    return {
        /**
         * Returns list of resource grants this app has on a team.
         * @param {AppsPermissionsResourcesApiGetResourcesListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResourcesList(requestParameters: AppsPermissionsResourcesApiGetResourcesListRequest, options?: AxiosRequestConfig): AxiosPromise<AppspermissionsresourcesGetResourcesListResponse> {
            return localVarFp.getResourcesList(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getResourcesList operation in AppsPermissionsResourcesApi.
 * @export
 * @interface AppsPermissionsResourcesApiGetResourcesListRequest
 */
export type AppsPermissionsResourcesApiGetResourcesListRequest = {
    
    /**
    * Authentication token. Requires scope: `none`
    * @type {string}
    * @memberof AppsPermissionsResourcesApiGetResourcesList
    */
    readonly token: string
    
    /**
    * Paginate through collections of data by setting the `cursor` parameter to a `next_cursor` attribute returned by a previous request\'s `response_metadata`. Default value fetches the first \"page\" of the collection. See [pagination](https://slack.dev) for more detail.
    * @type {string}
    * @memberof AppsPermissionsResourcesApiGetResourcesList
    */
    readonly cursor?: string
    
    /**
    * The maximum number of items to return.
    * @type {number}
    * @memberof AppsPermissionsResourcesApiGetResourcesList
    */
    readonly limit?: number
    
}

/**
 * AppsPermissionsResourcesApiGenerated - object-oriented interface
 * @export
 * @class AppsPermissionsResourcesApiGenerated
 * @extends {BaseAPI}
 */
export class AppsPermissionsResourcesApiGenerated extends BaseAPI {
    /**
     * Returns list of resource grants this app has on a team.
     * @param {AppsPermissionsResourcesApiGetResourcesListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppsPermissionsResourcesApiGenerated
     */
    public getResourcesList(requestParameters: AppsPermissionsResourcesApiGetResourcesListRequest, options?: AxiosRequestConfig) {
        return AppsPermissionsResourcesApiFp(this.configuration).getResourcesList(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
