/* tslint:disable */
/* eslint-disable */
/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ChatscheduledMessagesListResponse } from '../models';
// @ts-ignore
import { ChatscheduledMessagesListdefaultResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ChatScheduledMessagesApi - axios parameter creator
 * @export
 */
export const ChatScheduledMessagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a list of scheduled messages.
         * @param {string} [token] Authentication token. Requires scope: &#x60;none&#x60;
         * @param {string} [channel] The channel of the scheduled messages
         * @param {number} [latest] A UNIX timestamp of the latest value in the time range
         * @param {number} [oldest] A UNIX timestamp of the oldest value in the time range
         * @param {number} [limit] Maximum number of original entries to return.
         * @param {string} [cursor] For pagination purposes, this is the &#x60;cursor&#x60; value returned from a previous call to &#x60;chat.scheduledmessages.list&#x60; indicating where you want to start this call from.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (token?: string, channel?: string, latest?: number, oldest?: number, limit?: number, cursor?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/chat.scheduledMessages.list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication slackAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "slackAuth", ["none"], configuration)
            if (channel !== undefined) {
                localVarQueryParameter['channel'] = channel;
            }

            if (latest !== undefined) {
                localVarQueryParameter['latest'] = latest;
            }

            if (oldest !== undefined) {
                localVarQueryParameter['oldest'] = oldest;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (token != null) {
                localVarHeaderParameter['token'] = String(token);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/chat.scheduledMessages.list',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatScheduledMessagesApi - functional programming interface
 * @export
 */
export const ChatScheduledMessagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatScheduledMessagesApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a list of scheduled messages.
         * @param {ChatScheduledMessagesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: ChatScheduledMessagesApiListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatscheduledMessagesListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.token, requestParameters.channel, requestParameters.latest, requestParameters.oldest, requestParameters.limit, requestParameters.cursor, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ChatScheduledMessagesApi - factory interface
 * @export
 */
export const ChatScheduledMessagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatScheduledMessagesApiFp(configuration)
    return {
        /**
         * Returns a list of scheduled messages.
         * @param {ChatScheduledMessagesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: ChatScheduledMessagesApiListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<ChatscheduledMessagesListResponse> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for list operation in ChatScheduledMessagesApi.
 * @export
 * @interface ChatScheduledMessagesApiListRequest
 */
export type ChatScheduledMessagesApiListRequest = {
    
    /**
    * Authentication token. Requires scope: `none`
    * @type {string}
    * @memberof ChatScheduledMessagesApiList
    */
    readonly token?: string
    
    /**
    * The channel of the scheduled messages
    * @type {string}
    * @memberof ChatScheduledMessagesApiList
    */
    readonly channel?: string
    
    /**
    * A UNIX timestamp of the latest value in the time range
    * @type {number}
    * @memberof ChatScheduledMessagesApiList
    */
    readonly latest?: number
    
    /**
    * A UNIX timestamp of the oldest value in the time range
    * @type {number}
    * @memberof ChatScheduledMessagesApiList
    */
    readonly oldest?: number
    
    /**
    * Maximum number of original entries to return.
    * @type {number}
    * @memberof ChatScheduledMessagesApiList
    */
    readonly limit?: number
    
    /**
    * For pagination purposes, this is the `cursor` value returned from a previous call to `chat.scheduledmessages.list` indicating where you want to start this call from.
    * @type {string}
    * @memberof ChatScheduledMessagesApiList
    */
    readonly cursor?: string
    
}

/**
 * ChatScheduledMessagesApiGenerated - object-oriented interface
 * @export
 * @class ChatScheduledMessagesApiGenerated
 * @extends {BaseAPI}
 */
export class ChatScheduledMessagesApiGenerated extends BaseAPI {
    /**
     * Returns a list of scheduled messages.
     * @param {ChatScheduledMessagesApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatScheduledMessagesApiGenerated
     */
    public list(requestParameters: ChatScheduledMessagesApiListRequest = {}, options?: AxiosRequestConfig) {
        return ChatScheduledMessagesApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
