/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdminteamssettingsSetDefaultChannelsRequest
 */
export interface AdminteamssettingsSetDefaultChannelsRequest {
    /**
     * An array of channel IDs.
     * @type {string}
     * @memberof AdminteamssettingsSetDefaultChannelsRequest
     */
    'channel_ids': string;
    /**
     * ID for the workspace to set the default channel for.
     * @type {string}
     * @memberof AdminteamssettingsSetDefaultChannelsRequest
     */
    'team_id': string;
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     * @type {string}
     * @memberof AdminteamssettingsSetDefaultChannelsRequest
     */
    'token': string;
}

