/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdminconversationsCreateChannelBasedConversationRequest
 */
export interface AdminconversationsCreateChannelBasedConversationRequest {
    /**
     * Description of the public or private channel to create.
     * @type {string}
     * @memberof AdminconversationsCreateChannelBasedConversationRequest
     */
    'description'?: string;
    /**
     * When `true`, creates a private channel instead of a public channel
     * @type {boolean}
     * @memberof AdminconversationsCreateChannelBasedConversationRequest
     */
    'is_private': boolean;
    /**
     * Name of the public or private channel to create.
     * @type {string}
     * @memberof AdminconversationsCreateChannelBasedConversationRequest
     */
    'name': string;
    /**
     * When `true`, the channel will be available org-wide. Note: if the channel is not `org_wide=true`, you must specify a `team_id` for this channel
     * @type {boolean}
     * @memberof AdminconversationsCreateChannelBasedConversationRequest
     */
    'org_wide'?: boolean;
    /**
     * The workspace to create the channel in. Note: this argument is required unless you set `org_wide=true`.
     * @type {string}
     * @memberof AdminconversationsCreateChannelBasedConversationRequest
     */
    'team_id'?: string;
}

