/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdminusergroupsAssociateDefaultWorkspacesRequest
 */
export interface AdminusergroupsAssociateDefaultWorkspacesRequest {
    /**
     * When `true`, this method automatically creates new workspace accounts for the IDP group members.
     * @type {boolean}
     * @memberof AdminusergroupsAssociateDefaultWorkspacesRequest
     */
    'auto_provision'?: boolean;
    /**
     * A comma separated list of encoded team (workspace) IDs. Each workspace *MUST* belong to the organization associated with the token.
     * @type {string}
     * @memberof AdminusergroupsAssociateDefaultWorkspacesRequest
     */
    'team_ids': string;
    /**
     * An encoded usergroup (IDP Group) ID.
     * @type {string}
     * @memberof AdminusergroupsAssociateDefaultWorkspacesRequest
     */
    'usergroup_id': string;
}

