/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AdminemojiRemoveEnterpriseEmojiRequest
 */
export interface AdminemojiRemoveEnterpriseEmojiRequest {
    /**
     * The name of the emoji to be removed. Colons (`:myemoji:`) around the value are not required, although they may be included.
     * @type {string}
     * @memberof AdminemojiRemoveEnterpriseEmojiRequest
     */
    'name': string;
    /**
     * Authentication token. Requires scope: `admin.teams:write`
     * @type {string}
     * @memberof AdminemojiRemoveEnterpriseEmojiRequest
     */
    'token': string;
}

