/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppspermissionsscopesGetListResponseScopes
 */
export interface AppspermissionsscopesGetListResponseScopes {
    [key: string]: any;

    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'app_home'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'channel'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'group'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'im'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'mpim'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'team'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppspermissionsscopesGetListResponseScopes
     */
    'user'?: Array<string>;
}

