/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';

/**
 * Schema for successful response auth.test method
 * @export
 * @interface AuthTestResponse
 */
export interface AuthTestResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthTestResponse
     */
    'bot_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthTestResponse
     */
    'is_enterprise_install'?: boolean;
    /**
     * 
     * @type {DefsOkTrue}
     * @memberof AuthTestResponse
     */
    'ok': DefsOkTrue;
    /**
     * 
     * @type {string}
     * @memberof AuthTestResponse
     */
    'team': string;
    /**
     * 
     * @type {string}
     * @memberof AuthTestResponse
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof AuthTestResponse
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof AuthTestResponse
     */
    'user': string;
    /**
     * 
     * @type {string}
     * @memberof AuthTestResponse
     */
    'user_id': string;
}

