/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CallsAddRequest
 */
export interface CallsAddRequest {
    /**
     * The name of the Call.
     * @type {string}
     * @memberof CallsAddRequest
     */
    'title'?: string;
    /**
     * The valid Slack user ID of the user who created this Call. When this method is called with a user token, the `created_by` field is optional and defaults to the authed user of the token. Otherwise, the field is required.
     * @type {string}
     * @memberof CallsAddRequest
     */
    'created_by'?: string;
    /**
     * Call start time in UTC UNIX timestamp format
     * @type {number}
     * @memberof CallsAddRequest
     */
    'date_start'?: number;
    /**
     * When supplied, available Slack clients will attempt to directly launch the 3rd-party Call with this URL.
     * @type {string}
     * @memberof CallsAddRequest
     */
    'desktop_app_join_url'?: string;
    /**
     * An optional, human-readable ID supplied by the 3rd-party Call provider. If supplied, this ID will be displayed in the Call object.
     * @type {string}
     * @memberof CallsAddRequest
     */
    'external_display_id'?: string;
    /**
     * An ID supplied by the 3rd-party Call provider. It must be unique across all Calls from that service.
     * @type {string}
     * @memberof CallsAddRequest
     */
    'external_unique_id': string;
    /**
     * The URL required for a client to join the Call.
     * @type {string}
     * @memberof CallsAddRequest
     */
    'join_url': string;
    /**
     * The list of users to register as participants in the Call. [Read more on how to specify users here](https://slack.dev).
     * @type {string}
     * @memberof CallsAddRequest
     */
    'users'?: string;
}

