/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CallsparticipantsAddNewParticipantRequest
 */
export interface CallsparticipantsAddNewParticipantRequest {
    /**
     * `id` returned by the [`calls.add`](https://slack.dev) method.
     * @type {string}
     * @memberof CallsparticipantsAddNewParticipantRequest
     */
    'id': string;
    /**
     * The list of users to add as participants in the Call. [Read more on how to specify users here](https://slack.dev).
     * @type {string}
     * @memberof CallsparticipantsAddNewParticipantRequest
     */
    'users': string;
}

