/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CallsEndRequest
 */
export interface CallsEndRequest {
    /**
     * Call duration in seconds
     * @type {number}
     * @memberof CallsEndRequest
     */
    'duration'?: number;
    /**
     * `id` returned when registering the call using the [`calls.add`](https://slack.dev) method.
     * @type {string}
     * @memberof CallsEndRequest
     */
    'id': string;
}

