/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ChatDeleteRequest
 */
export interface ChatDeleteRequest {
    /**
     * Pass true to delete the message as the authed user with `chat:write:user` scope. [Bot users](https://slack.dev) in this context are considered authed users. If unused or false, the message will be deleted with `chat:write:bot` scope.
     * @type {boolean}
     * @memberof ChatDeleteRequest
     */
    'as_user'?: boolean;
    /**
     * Channel containing the message to be deleted.
     * @type {string}
     * @memberof ChatDeleteRequest
     */
    'channel'?: string;
    /**
     * Timestamp of the message to be deleted.
     * @type {number}
     * @memberof ChatDeleteRequest
     */
    'ts'?: number;
}

