/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConversationObjectDisplayCounts } from './conversation-object-display-counts';
import { ConversationObjectParentConversationInner } from './conversation-object-parent-conversation-inner';
import { ConversationObjectSharesInner } from './conversation-object-shares-inner';
import { ObjsChannelLatestInner } from './objs-channel-latest-inner';
import { ObjsChannelPurpose } from './objs-channel-purpose';

/**
 * 
 * @export
 * @interface ConversationObject
 */
export interface ConversationObject {
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'version'?: number;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'accepted_user'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'connected_team_ids'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'conversation_host_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'created': number;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'creator': string;
    /**
     * 
     * @type {ConversationObjectDisplayCounts}
     * @memberof ConversationObject
     */
    'display_counts'?: ConversationObjectDisplayCounts;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'enterprise_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'has_pins'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'id': string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'internal_team_ids'?: Set<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_archived': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_channel': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_ext_shared'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_frozen'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_general': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_global_shared'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_group': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_im': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_member'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'is_moved'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_mpim': ConversationObjectIsMpimEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_non_threadable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_open'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_org_default'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_org_mandatory'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_org_shared': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_pending_ext_shared'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_private': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_read_only'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_shared': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_starred'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationObject
     */
    'is_thread_only'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'last_read'?: string;
    /**
     * 
     * @type {Array<ObjsChannelLatestInner>}
     * @memberof ConversationObject
     */
    'latest'?: Array<ObjsChannelLatestInner>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'members'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'name_normalized': string;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'num_members'?: number;
    /**
     * 
     * @type {Array<ConversationObjectParentConversationInner>}
     * @memberof ConversationObject
     */
    'parent_conversation'?: Array<ConversationObjectParentConversationInner>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'pending_connected_team_ids'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'pending_shared'?: Set<string>;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'pin_count'?: number;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'previous_names'?: Set<string>;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'priority'?: number;
    /**
     * 
     * @type {ObjsChannelPurpose}
     * @memberof ConversationObject
     */
    'purpose': ObjsChannelPurpose;
    /**
     * 
     * @type {Set<string>}
     * @memberof ConversationObject
     */
    'shared_team_ids'?: Set<string>;
    /**
     * 
     * @type {Set<ConversationObjectSharesInner>}
     * @memberof ConversationObject
     */
    'shares'?: Set<ConversationObjectSharesInner>;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'timezone_count'?: number;
    /**
     * 
     * @type {ObjsChannelPurpose}
     * @memberof ConversationObject
     */
    'topic': ObjsChannelPurpose;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'unlinked'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'unread_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationObject
     */
    'unread_count_display'?: number;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'use_case'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationObject
     */
    'user'?: string;
}

type ConversationObjectIsMpimEnum = false


