/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkFalse } from './defs-ok-false';

/**
 * Schema for error response from conversations.join method
 * @export
 * @interface ConversationsJoindefaultResponse
 */
export interface ConversationsJoindefaultResponse {
    /**
     * Note: PHP callstack is only visible in dev/qa
     * @type {string}
     * @memberof ConversationsJoindefaultResponse
     */
    'callstack'?: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationsJoindefaultResponse
     */
    'error': ConversationsJoindefaultResponseErrorEnum;
    /**
     * 
     * @type {string}
     * @memberof ConversationsJoindefaultResponse
     */
    'needed'?: string;
    /**
     * 
     * @type {DefsOkFalse}
     * @memberof ConversationsJoindefaultResponse
     */
    'ok': DefsOkFalse;
    /**
     * 
     * @type {string}
     * @memberof ConversationsJoindefaultResponse
     */
    'provided'?: string;
}

type ConversationsJoindefaultResponseErrorEnum = 'method_not_supported_for_channel_type' | 'missing_scope' | 'channel_not_found' | 'is_archived' | 'not_authed' | 'invalid_auth' | 'account_inactive' | 'user_is_bot' | 'user_is_restricted' | 'user_is_ultra_restricted' | 'invalid_arg_name' | 'invalid_array_arg' | 'invalid_charset' | 'invalid_form_data' | 'invalid_post_type' | 'missing_post_type' | 'invalid_json' | 'json_not_object' | 'request_timeout' | 'upgrade_required' | 'team_added_to_org' | 'missing_charset' | 'superfluous_charset'


