/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConversationIMChannelObjectFromConversationsMethodsSharesInner } from './conversation-imchannel-object-from-conversations-methods-shares-inner';
import { ConversationObjectParentConversationInner } from './conversation-object-parent-conversation-inner';
import { ObjsChannelLatestInner } from './objs-channel-latest-inner';

/**
 * 
 * @export
 * @interface ConversationIMChannelObjectFromConversationsMethods
 */
export interface ConversationIMChannelObjectFromConversationsMethods {
    /**
     * 
     * @type {number}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'version'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'created': number;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'has_pins'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_archived'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_ext_shared'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_frozen'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_im': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_open'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_org_shared': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_shared'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_starred'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'is_user_deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'last_read'?: string;
    /**
     * 
     * @type {Array<ObjsChannelLatestInner>}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'latest'?: Array<ObjsChannelLatestInner>;
    /**
     * 
     * @type {Array<ConversationObjectParentConversationInner>}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'parent_conversation'?: Array<ConversationObjectParentConversationInner>;
    /**
     * 
     * @type {number}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'pin_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'priority': number;
    /**
     * 
     * @type {Set<ConversationIMChannelObjectFromConversationsMethodsSharesInner>}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'shares'?: Set<ConversationIMChannelObjectFromConversationsMethodsSharesInner>;
    /**
     * 
     * @type {number}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'unread_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'unread_count_display'?: number;
    /**
     * 
     * @type {string}
     * @memberof ConversationIMChannelObjectFromConversationsMethods
     */
    'user': string;
}

