/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FilesremoteUpdateRemoteFileRequest
 */
export interface FilesremoteUpdateRemoteFileRequest {
    /**
     * Title of the file being shared.
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'title'?: string;
    /**
     * Creator defined GUID for the file.
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'external_id'?: string;
    /**
     * URL of the remote file.
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'external_url'?: string;
    /**
     * Specify a file by providing its ID.
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'file'?: string;
    /**
     * type of file
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'filetype'?: string;
    /**
     * File containing contents that can be used to improve searchability for the remote file.
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'indexable_file_contents'?: string;
    /**
     * Preview of the document via `multipart/form-data`.
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'preview_image'?: string;
    /**
     * Authentication token. Requires scope: `remote_files:write`
     * @type {string}
     * @memberof FilesremoteUpdateRemoteFileRequest
     */
    'token'?: string;
}

