/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';
import { ObjsFile } from './objs-file';
import { ObjsPaging } from './objs-paging';

/**
 * Schema for successful response from files.list method
 * @export
 * @interface FilesListResponse
 */
export interface FilesListResponse {
    /**
     * 
     * @type {Set<ObjsFile>}
     * @memberof FilesListResponse
     */
    'files': Set<ObjsFile>;
    /**
     * 
     * @type {DefsOkTrue}
     * @memberof FilesListResponse
     */
    'ok': DefsOkTrue;
    /**
     * 
     * @type {ObjsPaging}
     * @memberof FilesListResponse
     */
    'paging': ObjsPaging;
}

