/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsReaction } from './objs-reaction';

/**
 * 
 * @export
 * @interface ObjsComment
 */
export interface ObjsComment {
    /**
     * 
     * @type {string}
     * @memberof ObjsComment
     */
    'comment': string;
    /**
     * 
     * @type {number}
     * @memberof ObjsComment
     */
    'created': number;
    /**
     * 
     * @type {string}
     * @memberof ObjsComment
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsComment
     */
    'is_intro': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsComment
     */
    'is_starred'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjsComment
     */
    'num_stars'?: number;
    /**
     * 
     * @type {object}
     * @memberof ObjsComment
     */
    'pinned_info'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof ObjsComment
     */
    'pinned_to'?: Array<string>;
    /**
     * 
     * @type {Array<ObjsReaction>}
     * @memberof ObjsComment
     */
    'reactions'?: Array<ObjsReaction>;
    /**
     * 
     * @type {number}
     * @memberof ObjsComment
     */
    'timestamp': number;
    /**
     * 
     * @type {string}
     * @memberof ObjsComment
     */
    'user': string;
}

