/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsFileShares } from './objs-file-shares';
import { ObjsReaction } from './objs-reaction';

/**
 * 
 * @export
 * @interface ObjsFile
 */
export interface ObjsFile {
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'title'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ObjsFile
     */
    'channels'?: Set<string>;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'comments_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'created'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'date_delete'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'display_as_bot'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'editable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'editor'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'external_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'external_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'external_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'filetype'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ObjsFile
     */
    'groups'?: Set<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'has_rich_preview'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'image_exif_rotation'?: number;
    /**
     * 
     * @type {Set<string>}
     * @memberof ObjsFile
     */
    'ims'?: Set<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'is_external'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'is_public'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'is_starred'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'is_tombstoned'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'last_editor'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'mimetype'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'mode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'non_owner_editable'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'num_stars'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'original_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'original_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'permalink'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'permalink_public'?: string;
    /**
     * 
     * @type {object}
     * @memberof ObjsFile
     */
    'pinned_info'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof ObjsFile
     */
    'pinned_to'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'pretty_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'preview'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsFile
     */
    'public_url_shared'?: boolean;
    /**
     * 
     * @type {Array<ObjsReaction>}
     * @memberof ObjsFile
     */
    'reactions'?: Array<ObjsReaction>;
    /**
     * 
     * @type {ObjsFileShares}
     * @memberof ObjsFile
     */
    'shares'?: ObjsFileShares;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'source_team'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_1024'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_1024_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_1024_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_160'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_360'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_360_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_360_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_480'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_480_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_480_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_64'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_720'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_720_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_720_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_80'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_800'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_800_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_800_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_960'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_960_h'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'thumb_960_w'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'thumb_tiny'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'timestamp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsFile
     */
    'updated'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'url_private'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'url_private_download'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'user'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'user_team'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjsFile
     */
    'username'?: string;
}

