/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsSubteamAutoTypeInner } from './objs-subteam-auto-type-inner';
import { ObjsSubteamDeletedByInner } from './objs-subteam-deleted-by-inner';
import { ObjsSubteamPrefs } from './objs-subteam-prefs';

/**
 * 
 * @export
 * @interface ObjsSubteam
 */
export interface ObjsSubteam {
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'description': string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsSubteam
     */
    'auto_provision': boolean;
    /**
     * 
     * @type {Array<ObjsSubteamAutoTypeInner>}
     * @memberof ObjsSubteam
     */
    'auto_type': Array<ObjsSubteamAutoTypeInner>;
    /**
     * 
     * @type {number}
     * @memberof ObjsSubteam
     */
    'channel_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'created_by': string;
    /**
     * 
     * @type {number}
     * @memberof ObjsSubteam
     */
    'date_create': number;
    /**
     * 
     * @type {number}
     * @memberof ObjsSubteam
     */
    'date_delete': number;
    /**
     * 
     * @type {number}
     * @memberof ObjsSubteam
     */
    'date_update': number;
    /**
     * 
     * @type {Array<ObjsSubteamDeletedByInner>}
     * @memberof ObjsSubteam
     */
    'deleted_by': Array<ObjsSubteamDeletedByInner>;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'enterprise_subteam_id': string;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'handle': string;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsSubteam
     */
    'is_external': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsSubteam
     */
    'is_subteam': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsSubteam
     */
    'is_usergroup': boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'name': string;
    /**
     * 
     * @type {ObjsSubteamPrefs}
     * @memberof ObjsSubteam
     */
    'prefs': ObjsSubteamPrefs;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'team_id': string;
    /**
     * 
     * @type {string}
     * @memberof ObjsSubteam
     */
    'updated_by': string;
    /**
     * 
     * @type {number}
     * @memberof ObjsSubteam
     */
    'user_count'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ObjsSubteam
     */
    'users'?: Array<string>;
}

