/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsChannelLatestInner } from './objs-channel-latest-inner';
import { ObjsChannelPurpose } from './objs-channel-purpose';

/**
 * 
 * @export
 * @interface ObjsChannel
 */
export interface ObjsChannel {
    /**
     * 
     * @type {string}
     * @memberof ObjsChannel
     */
    'accepted_user'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'created': number;
    /**
     * 
     * @type {string}
     * @memberof ObjsChannel
     */
    'creator': string;
    /**
     * 
     * @type {string}
     * @memberof ObjsChannel
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_archived'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_channel': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_frozen'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_general'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_member'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'is_moved'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_mpim': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_non_threadable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_org_shared': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_pending_ext_shared'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_private': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_read_only'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_shared': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsChannel
     */
    'is_thread_only'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjsChannel
     */
    'last_read'?: string;
    /**
     * 
     * @type {Array<ObjsChannelLatestInner>}
     * @memberof ObjsChannel
     */
    'latest'?: Array<ObjsChannelLatestInner>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ObjsChannel
     */
    'members': Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ObjsChannel
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ObjsChannel
     */
    'name_normalized': string;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'num_members'?: number;
    /**
     * 
     * @type {Set<string>}
     * @memberof ObjsChannel
     */
    'pending_shared'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof ObjsChannel
     */
    'previous_names'?: Set<string>;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'priority'?: number;
    /**
     * 
     * @type {ObjsChannelPurpose}
     * @memberof ObjsChannel
     */
    'purpose': ObjsChannelPurpose;
    /**
     * 
     * @type {ObjsChannelPurpose}
     * @memberof ObjsChannel
     */
    'topic': ObjsChannelPurpose;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'unlinked'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'unread_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjsChannel
     */
    'unread_count_display'?: number;
}

