/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BlocksInner } from './blocks-inner';
import { ObjsBotProfile } from './objs-bot-profile';
import { ObjsComment } from './objs-comment';
import { ObjsFile } from './objs-file';
import { ObjsMessage } from './objs-message';
import { ObjsMessageAttachmentsInner } from './objs-message-attachments-inner';
import { ObjsMessageBotIdInner } from './objs-message-bot-id-inner';
import { ObjsMessageIcons } from './objs-message-icons';
import { ObjsReaction } from './objs-reaction';
import { ObjsUserProfileShort } from './objs-user-profile-short';

/**
 * @type ObjsChannelLatestInner
 * @export
 */
export type ObjsChannelLatestInner = ObjsMessage;


