/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsResourcesExcludedIdsInnerInner } from './objs-resources-excluded-ids-inner-inner';

/**
 * 
 * @export
 * @interface ObjsResources
 */
export interface ObjsResources {
    /**
     * 
     * @type {Array<Array<ObjsResourcesExcludedIdsInnerInner>>}
     * @memberof ObjsResources
     */
    'excluded_ids'?: Array<Array<ObjsResourcesExcludedIdsInnerInner>>;
    /**
     * 
     * @type {Array<Array<ObjsResourcesExcludedIdsInnerInner>>}
     * @memberof ObjsResources
     */
    'ids': Array<Array<ObjsResourcesExcludedIdsInnerInner>>;
    /**
     * 
     * @type {boolean}
     * @memberof ObjsResources
     */
    'wildcard'?: boolean;
}

