/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';
import { PinsListResponseInnerAnyOfItemsInner } from './pins-list-response-inner-any-of-items-inner';

/**
 * 
 * @export
 * @interface PinsListResponseInnerAnyOf
 */
export interface PinsListResponseInnerAnyOf {
    /**
     * 
     * @type {Set<PinsListResponseInnerAnyOfItemsInner>}
     * @memberof PinsListResponseInnerAnyOf
     */
    'items': Set<PinsListResponseInnerAnyOfItemsInner>;
    /**
     * 
     * @type {DefsOkTrue}
     * @memberof PinsListResponseInnerAnyOf
     */
    'ok': DefsOkTrue;
}

