/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsFile } from './objs-file';

/**
 * 
 * @export
 * @interface ReactionsListResponseItemsInnerInnerAnyOf1
 */
export interface ReactionsListResponseItemsInnerInnerAnyOf1 {
    /**
     * 
     * @type {ObjsFile}
     * @memberof ReactionsListResponseItemsInnerInnerAnyOf1
     */
    'file': ObjsFile;
    /**
     * 
     * @type {string}
     * @memberof ReactionsListResponseItemsInnerInnerAnyOf1
     */
    'type': ReactionsListResponseItemsInnerInnerAnyOf1TypeEnum;
}

type ReactionsListResponseItemsInnerInnerAnyOf1TypeEnum = 'file'


