/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReactionsAddRequest
 */
export interface ReactionsAddRequest {
    /**
     * Channel where the message to add reaction to was posted.
     * @type {string}
     * @memberof ReactionsAddRequest
     */
    'channel': string;
    /**
     * Reaction (emoji) name.
     * @type {string}
     * @memberof ReactionsAddRequest
     */
    'name': string;
    /**
     * Timestamp of the message to add reaction to.
     * @type {string}
     * @memberof ReactionsAddRequest
     */
    'timestamp': string;
}

