/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';
import { ObjsComment } from './objs-comment';
import { ObjsFile } from './objs-file';

/**
 * 
 * @export
 * @interface ReactionsGetResponseInnerAnyOf2
 */
export interface ReactionsGetResponseInnerAnyOf2 {
    /**
     * 
     * @type {ObjsComment}
     * @memberof ReactionsGetResponseInnerAnyOf2
     */
    'comment': ObjsComment;
    /**
     * 
     * @type {ObjsFile}
     * @memberof ReactionsGetResponseInnerAnyOf2
     */
    'file': ObjsFile;
    /**
     * 
     * @type {DefsOkTrue}
     * @memberof ReactionsGetResponseInnerAnyOf2
     */
    'ok': DefsOkTrue;
    /**
     * 
     * @type {string}
     * @memberof ReactionsGetResponseInnerAnyOf2
     */
    'type': ReactionsGetResponseInnerAnyOf2TypeEnum;
}

type ReactionsGetResponseInnerAnyOf2TypeEnum = 'file_comment'


