/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StarsAddRequest
 */
export interface StarsAddRequest {
    /**
     * Channel to add star to, or channel where the message to add star to was posted (used with `timestamp`).
     * @type {string}
     * @memberof StarsAddRequest
     */
    'channel'?: string;
    /**
     * File to add star to.
     * @type {string}
     * @memberof StarsAddRequest
     */
    'file'?: string;
    /**
     * File comment to add star to.
     * @type {string}
     * @memberof StarsAddRequest
     */
    'file_comment'?: string;
    /**
     * Timestamp of the message to add star to.
     * @type {string}
     * @memberof StarsAddRequest
     */
    'timestamp'?: string;
}

