/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsMessage } from './objs-message';

/**
 * 
 * @export
 * @interface StarsListResponseItemsInnerInnerAnyOf
 */
export interface StarsListResponseItemsInnerInnerAnyOf {
    /**
     * 
     * @type {string}
     * @memberof StarsListResponseItemsInnerInnerAnyOf
     */
    'channel': string;
    /**
     * 
     * @type {number}
     * @memberof StarsListResponseItemsInnerInnerAnyOf
     */
    'date_create': number;
    /**
     * 
     * @type {ObjsMessage}
     * @memberof StarsListResponseItemsInnerInnerAnyOf
     */
    'message': ObjsMessage;
    /**
     * 
     * @type {string}
     * @memberof StarsListResponseItemsInnerInnerAnyOf
     */
    'type': StarsListResponseItemsInnerInnerAnyOfTypeEnum;
}

type StarsListResponseItemsInnerInnerAnyOfTypeEnum = 'message'


