/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StarsListResponseItemsInnerInnerAnyOf3
 */
export interface StarsListResponseItemsInnerInnerAnyOf3 {
    /**
     * 
     * @type {string}
     * @memberof StarsListResponseItemsInnerInnerAnyOf3
     */
    'channel': string;
    /**
     * 
     * @type {number}
     * @memberof StarsListResponseItemsInnerInnerAnyOf3
     */
    'date_create': number;
    /**
     * 
     * @type {string}
     * @memberof StarsListResponseItemsInnerInnerAnyOf3
     */
    'type': StarsListResponseItemsInnerInnerAnyOf3TypeEnum;
}

type StarsListResponseItemsInnerInnerAnyOf3TypeEnum = 'channel'


