/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StarsRemoveRequest
 */
export interface StarsRemoveRequest {
    /**
     * Channel to remove star from, or channel where the message to remove star from was posted (used with `timestamp`).
     * @type {string}
     * @memberof StarsRemoveRequest
     */
    'channel'?: string;
    /**
     * File to remove star from.
     * @type {string}
     * @memberof StarsRemoveRequest
     */
    'file'?: string;
    /**
     * File comment to remove star from.
     * @type {string}
     * @memberof StarsRemoveRequest
     */
    'file_comment'?: string;
    /**
     * Timestamp of the message to remove star from.
     * @type {string}
     * @memberof StarsRemoveRequest
     */
    'timestamp'?: string;
}

