/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObjsComment } from './objs-comment';
import { ObjsFile } from './objs-file';
import { ObjsMessage } from './objs-message';
import { StarsListResponseItemsInnerInnerAnyOf } from './stars-list-response-items-inner-inner-any-of';
import { StarsListResponseItemsInnerInnerAnyOf1 } from './stars-list-response-items-inner-inner-any-of1';
import { StarsListResponseItemsInnerInnerAnyOf2 } from './stars-list-response-items-inner-inner-any-of2';
import { StarsListResponseItemsInnerInnerAnyOf3 } from './stars-list-response-items-inner-inner-any-of3';
import { StarsListResponseItemsInnerInnerAnyOf4 } from './stars-list-response-items-inner-inner-any-of4';
import { StarsListResponseItemsInnerInnerAnyOf5 } from './stars-list-response-items-inner-inner-any-of5';

/**
 * @type StarsListResponseItemsInnerInner
 * @export
 */
export type StarsListResponseItemsInnerInner = StarsListResponseItemsInnerInnerAnyOf | StarsListResponseItemsInnerInnerAnyOf1 | StarsListResponseItemsInnerInnerAnyOf2 | StarsListResponseItemsInnerInnerAnyOf3 | StarsListResponseItemsInnerInnerAnyOf4 | StarsListResponseItemsInnerInnerAnyOf5;


