/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TeamAccessLogsResponseLoginsInner
 */
export interface TeamAccessLogsResponseLoginsInner {
    /**
     * 
     * @type {number}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'country': string | null;
    /**
     * 
     * @type {number}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'date_first': number;
    /**
     * 
     * @type {number}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'date_last': number;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'ip': string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'isp': string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'region': string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'user_agent': string;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamAccessLogsResponseLoginsInner
     */
    'username': string;
}

