/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TeamIntegrationLogsResponseLogsInner
 */
export interface TeamIntegrationLogsResponseLogsInner {
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'admin_app_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'app_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'app_type': string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'change_type': string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'scope': string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'service_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'service_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof TeamIntegrationLogsResponseLogsInner
     */
    'user_name': string;
}

