/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';
import { ObjsPaging } from './objs-paging';
import { TeamAccessLogsResponseLoginsInner } from './team-access-logs-response-logins-inner';

/**
 * Schema for successful response from team.accessLogs method
 * @export
 * @interface TeamAccessLogsResponse
 */
export interface TeamAccessLogsResponse {
    /**
     * 
     * @type {Set<TeamAccessLogsResponseLoginsInner>}
     * @memberof TeamAccessLogsResponse
     */
    'logins': Set<TeamAccessLogsResponseLoginsInner>;
    /**
     * 
     * @type {DefsOkTrue}
     * @memberof TeamAccessLogsResponse
     */
    'ok': DefsOkTrue;
    /**
     * 
     * @type {ObjsPaging}
     * @memberof TeamAccessLogsResponse
     */
    'paging': ObjsPaging;
}

