/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';
import { RtmConnectResponseSelf } from './rtm-connect-response-self';
import { UsersIdentityResponseInnerAnyOf } from './users-identity-response-inner-any-of';
import { UsersIdentityResponseInnerAnyOf1 } from './users-identity-response-inner-any-of1';
import { UsersIdentityResponseInnerAnyOf2 } from './users-identity-response-inner-any-of2';
import { UsersIdentityResponseInnerAnyOf3 } from './users-identity-response-inner-any-of3';
import { UsersIdentityResponseInnerAnyOf3Team } from './users-identity-response-inner-any-of3-team';

/**
 * @type UsersIdentityResponseInner
 * @export
 */
export type UsersIdentityResponseInner = UsersIdentityResponseInnerAnyOf | UsersIdentityResponseInnerAnyOf1 | UsersIdentityResponseInnerAnyOf2 | UsersIdentityResponseInnerAnyOf3;


