/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UsersprofileSetProfileInfoRequest
 */
export interface UsersprofileSetProfileInfoRequest {
    /**
     * Name of a single key to set. Usable only if `profile` is not passed.
     * @type {string}
     * @memberof UsersprofileSetProfileInfoRequest
     */
    'name'?: string;
    /**
     * Collection of key:value pairs presented as a URL-encoded JSON hash. At most 50 fields may be set. Each field name is limited to 255 characters.
     * @type {string}
     * @memberof UsersprofileSetProfileInfoRequest
     */
    'profile'?: string;
    /**
     * ID of user to change. This argument may only be specified by team admins on paid teams.
     * @type {string}
     * @memberof UsersprofileSetProfileInfoRequest
     */
    'user'?: string;
    /**
     * Value to set a single key to. Usable only if `profile` is not passed.
     * @type {string}
     * @memberof UsersprofileSetProfileInfoRequest
     */
    'value'?: string;
}

