/*
Slack Web API

One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

The version of the OpenAPI document: 1.7.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DefsOkTrue } from './defs-ok-true';

/**
 * Generated from users.getPresence with shasum e7251aec575d8863f9e0eb38663ae9dc26655f65
 * @export
 * @interface UsersGetPresenceResponse
 */
export interface UsersGetPresenceResponse {
    [key: string]: any;

    /**
     * 
     * @type {boolean}
     * @memberof UsersGetPresenceResponse
     */
    'auto_away'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UsersGetPresenceResponse
     */
    'connection_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersGetPresenceResponse
     */
    'last_activity'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UsersGetPresenceResponse
     */
    'manual_away'?: boolean;
    /**
     * 
     * @type {DefsOkTrue}
     * @memberof UsersGetPresenceResponse
     */
    'ok': DefsOkTrue;
    /**
     * 
     * @type {boolean}
     * @memberof UsersGetPresenceResponse
     */
    'online'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UsersGetPresenceResponse
     */
    'presence': string;
}

